apiVersion: skaffold/v1beta8
kind: Config
build:
  artifacts:
    - image: youtube-ex/youtube-ex
      context: cmd/web
deploy:
  helm:
    releases:
      - name: youtube-ex
        chartPath: deployment
        values:
          image: youtube-ex/youtube-ex
