apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: youtube-ex/api
    docker:
      dockerfile: ../../build/package/api.Dockerfile
    context: cmd/api
  - image: youtube-ex/mailer
    docker:
      dockerfile: ../../build/package/mailer.Dockerfile
    context: cmd/mailer
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
    - name: api
      namespace: youtube-ex
      chartPath: deployments/helm/api
      values:
        image: youtube-ex/api
    - name: mailer
      namespace: youtube-ex
      chartPath: deployments/helm/mailer
      values:
        image: youtube-ex/mailer
