apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: youtube-ex/api
    docker:
      dockerfile: ../../build/package/api.Dockerfile
    context: cmd/api
  - image: youtube-ex/mailer
    docker:
      dockerfile: ../../build/package/mailer.Dockerfile
    context: cmd/mailer
  - image: youtube-ex/front
    docker:
      dockerfile: ../../build/package/front.Dockerfile
    context: cmd/front
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
    - name: api
      chartPath: deployments/helm/api
      values:
        image: youtube-ex/api
    - name: mailer
      chartPath: deployments/helm/mailer
      values:
        image: youtube-ex/mailer
    - name: front
      chartPath: deployments/helm/front
      values:
        image: youtube-ex/front
