# YoutubeEx mailer main image
image: youtube-ex/mailer

# YoutubeEx mailer service configuration
service:
  # YoutubeEx mailer service type
  type: LoadBalancer
  # clusterIP: None
  port: 4047

# YoutubeEx mailer node replication number
replicas: 1

# Postfix configurations
postfix:
  smtp:
    domain: mailer
    password: DgZLmkh8xZGH3mmWWCdLnQE4f795HARPypVW2qEQNrSrc3JLdTAK3BWMTGVKAmma
    relay:
      enabled: false
  image:
    repository: shikanime/postfix
