apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mailer.fullname" . }}
  labels:
    app: {{ template "mailer.name" . }}
    chart: {{ template "mailer.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "mailer.name" . }}
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ template "mailer.name" . }}
        chart: {{ template "mailer.chart" . }}
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    spec:
      containers:
      - name: {{ template "mailer.fullname" . }}
        image: "{{ .Values.image }}"
        imagePullPolicy: "{{ .Values.pullPolicy }}"
        env:
        - name: POSTFIX_HOST
          value: {{ include "mailer.fullname" . }}-postfix
        - name: POSTFIX_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "mailer.fullname" . }}-postfix
              key: smtp_password
        - name: PORT
          value: "4047"
        ports:
        - name: api
          containerPort: 4047
