apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    app: {{ template "api.name" . }}
    chart: {{ template "api.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  serviceName: "web"
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "api.name" . }}
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ template "api.name" . }}
        chart: {{ template "api.chart" . }}
        release: {{ .Release.Name | quote }}
        heritage: {{ .Release.Service | quote }}
    spec:
      initContainers:
      - name: postgresql-readiness-check
        image: postgres
        imagePullPolicy: "{{ .Values.pullPolicy }}"
        command:
        - 'sh'
        - '-c'
        - until pg_isready -h {{ include "api.fullname" . }}-postgresql -p 5432; do
            sleep 2;
          done;
      - name: database-migration
        image: "{{ .Values.image }}"
        imagePullPolicy: "{{ .Values.pullPolicy }}"
        args: ["api", "eval", '"Api.Release.migrate()"']
        env:
        - name: POSTGRES_HOST
          value: {{ include "api.fullname" . }}-postgresql
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "api.fullname" . }}-postgresql
              key: postgresql-password
        - name: PHOENIX_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "api.fullname" . }}
              key: phoenix-secret
        - name: RELEASE_COOKIE
          valueFrom:
            secretKeyRef:
              name: {{ include "api.fullname" . }}
              key: erlang-cookie
        - name: RELEASE_NODE
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      containers:
      - name: {{ template "api.fullname" . }}
        image: "{{ .Values.image }}"
        imagePullPolicy: "{{ .Values.pullPolicy }}"
        env:
        - name: HOST
          value: {{ include "api.fullname" . }}
        - name: PORT
          value: "80"
        - name: POSTGRES_HOST
          value: {{ include "api.fullname" . }}-postgresql
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "api.fullname" . }}-postgresql
              key: postgresql-password
        - name: PHOENIX_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "api.fullname" . }}
              key: phoenix-secret
        - name: GOSSIP_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "api.fullname" . }}
              key: gossip-secret
        - name: RELEASE_COOKIE
          valueFrom:
            secretKeyRef:
              name: {{ include "api.fullname" . }}
              key: erlang-cookie
        - name: RELEASE_NODE
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: web
          containerPort: 80
        - name: erlang-daemon
          containerPort: 4369
        - name: erlang-discover
          containerPort: 45892
        - name: erlang-mesh-0
          containerPort: 49200
        - name: erlang-mesh-1
          containerPort: 49201
        - name: erlang-mesh-2
          containerPort: 49202
        - name: erlang-mesh-3
          containerPort: 49203
        - name: erlang-mesh-4
          containerPort: 49204
        - name: erlang-mesh-5
          containerPort: 49205
        - name: erlang-mesh-6
          containerPort: 49206
        - name: erlang-mesh-7
          containerPort: 49207
        - name: erlang-mesh-8
          containerPort: 49208
        - name: erlang-mesh-9
          containerPort: 49209
        - name: erlang-mesh-10
          containerPort: 49210
