# YoutubeExWeb main image
image: youtube-ex/api

# YoutubeExWeb service configuration
service:
  # YoutubeExWeb service type
  type: LoadBalancer
  # clusterIP: None
  port: 80

# YoutubeExWeb Gossip discovery secret
gossipSecret: Yy1d/NKVUWXnHvps8YAG82IhliY1Qa8nfhl+Qt9eKTioRKtsW4J0lUL4tankbk3R

# YoutubeExWeb Gossip discovery secret
phoenixSecret: JScUlQe+INcOfoMn+JG3RQP8BCu+QbKNy5ByCUxlsufJLPXt7DpyZId0DU/iODcR

# YoutubeExWeb Erlang distribution cookie
erlangCookie: jeAuFKBxxxTth0LrbTDncsyFOdGWqNCgPXaLjdl5hc65Ec+WLrYXL5nmPdnRp3LG

# YoutubeExWeb node replication number
replicas: 1

# PostgreSQL credentials
postgresql:
  postgresqlUsername: api
  postgresqlPassword: Jn3QJrnw7pnSjFSR
  postgresqlDatabase: api
