import Config

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# ElasticSearch endpoint
config :api_search, Api.Search.Client, hostname: "localhost:9200"

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Configure your database
config :api, Api.Repo,
  username: "postgres",
  password: "postgres",
  database: "api_dev",
  hostname: "localhost",
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :api_web, Api.Web.Endpoint,
  url: [host: "localhost"],
  secret_key_base: "TxKULpxOaPXk40uyol9BwpfJDGqxqHUpO6tvdBJde9gIGTulK0MiQPDvRIbqt+fq",
  server: true,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: []

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Cluster discovery
config :libcluster,
  gossip_secret: "7dpG02D6M/6GbzIVkgr46YuoPvKiau9jVnTMNE6AE4hA/vDFsHg6dxsV+y0VikpM"
